name: Deploy to EC2
 
on:
  push:
    branches:
      - main
 
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
 
      - name: Set up Java
        uses: actions/setup-java@v1
        with:
          java-version: '21'
 
      - name: Set up Maven Wrapper
        run: mvn -N io.takari:maven:wrapper
 
      - name: Build Spring Boot application
        run: |
          chmod +x mvnw
          ./mvnw package -DskipTests
 
      - name: Copy JAR file to EC2
        uses: appleboy/scp-action@master
        with:
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
           aws s3 cp target/demo-0.0.1-SNAPSHOT.jar s3://s3instancepro/
 
      - name: SSH into EC2 and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            cd demo-0.0.1-SNAPSHOT.jar/target
            java -jar demo-0.0.1-SNAPSHOT.jar
 
