name: Deploy to EC2
 
on:
  push:
    branches:
      - main
 
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
 
      - name: Set up Java
        uses: actions/setup-java@v1
        with:
          java-version: '21'
 
      - name: Set up Maven Wrapper
        run: mvn -N io.takari:maven:wrapper
 
      - name: Build Spring Boot application
        run: |
          chmod +x mvnw
          ./mvnw package -DskipTests
 
      - name: Stop old running server
        uses: appleboy/ssh-action@master
        with:
          host: 54.220.202.86
          username: ec2-user
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            cd /home/ec2-user/demo-0.0.1-SNAPSHOT.jar/target
            nohup pkill -f demo-0.0.1-SNAPSHOT.jar > output.log 2>&1 &
            echo "Java process stopped."
 
 
      - name: Copy JAR file to EC2
        uses: appleboy/scp-action@master
        with:
          host: 54.220.202.86
          username: ec2-user
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          source: 'target/demo-0.0.1-SNAPSHOT.jar'
          target: '/home/ec2-user/demo-0.0.1-SNAPSHOT.jar'
 
      - name: SSH into EC2 and deploy
        uses: appleboy/ssh-action@master
        with:
          host: 54.220.202.86
          username: ec2-user
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            cd /home/ec2-user/demo-0.0.1-SNAPSHOT.jar/target
            nohup java -jar demo-0.0.1-SNAPSHOT.jar > output.log 2>&1 &
            echo "Java process started."
