name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '21'  # Updated to Java 17 for compatibility
          cache: 'maven'
          cache-dependency-path: 'sub-project/pom.xml'  # optional

      - name: Build with Maven
        run: mvn -B package --file pom.xml

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Install AWS CLI
        run: pip3 install awscli

      - name: Debugging
        run: |
          ls -la
          find . -name 'demo-0.0.1-SNAPSHOT.jar'

      - name: Upload JAR to S3
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            ssh -v -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null user@host "echo Hello"
            aws s3 cp target/demo-0.0.1-SNAPSHOT.jar s3://s3instancepro/
