name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Maven Wrapper
        run: mvn -N io.takari:maven:wrapper

      - name: Set up Java
        uses: actions/setup-java@v1
        with:
          java-version: '21'
 
      - name: Build Spring Boot application
        run: |
          chmod +x mvnw
          ./mvnw package -DskipTests

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Install AWS CLI
        run: pip3 install awscli
        
      - name: Upload JAR to S3
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            ssh -v -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} "echo Hello"
            aws s3 cp target/demo-0.0.1-SNAPSHOT.jar s3://s3instancepro/

      - name: SSH into EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
             aws s3 cp s3://s3instancepro/demo-0.0.1-SNAPSHOT.jar /home/ec2-user/
             java -jar /home/ec2-user/demo-0.0.1-SNAPSHOT.jar
