name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '21'
        cache: 'maven'
        cache-dependency-path: 'sub-project/pom.xml'  # optional

    - name: Build with Maven
	
      run: mvn -B package --file pom.xml

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Install AWS CLI
      run: |
        sudo apt-get install -y python3-pip
        pip3 install awscli

    - name: Upload JAR to S3
      run: |
        aws s3 cp target/demo-0.0.1-SNAPSHOT.jar s3://s3instancepro/

    - name: SSH into EC2
      uses: appleboy/ssh-action@v3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_PRIVATE_KEY }}
        script: |
          # Fetch JAR from S3 bucket
          aws s3 cp s3://s3instancepro/demo-0.0.1-SNAPSHOT.jar //home/ec2-user/

          # Run the Spring Boot application
          java -jar /home/ec2-user/demo-0.0.1-SNAPSHOT.jar
