name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'
          cache-dependency-path: 'sub-project/pom.xml'  # optional

      - name: Build with Maven
        run: mvn -B package --file pom.xml

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Install AWS CLI
        run: pip3 install awscli

      - name: Update known_hosts
        run: ssh-keyscan -H ${{ secrets.EC2_HOST }} >> $HOME/.ssh/known_hosts

      - name: Debugging
        run: |
          ls -la target/
          find . -name 'demo-0.0.1-SNAPSHOT.jar'

      - name: Upload JAR to S3
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            eval $(ssh-agent)
            ssh-add <(echo "${{ secrets.EC2_PRIVATE_KEY }}")
            aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws configure set aws_session_token ${{ secrets.AWS_SESSION_TOKEN }}

            # Debugging: List files in the target directory
            ls -la target/

            # Debugging: Find the JAR file
            find . -name 'demo-0.0.1-SNAPSHOT.jar'

            # Copy JAR file to S3
            aws s3 cp target/demo-0.0.1-SNAPSHOT.jar s3://s3instancepro/

      - name: SSH into EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            # Fetch JAR from S3 bucket
            aws s3 cp s3://s3instancepro/demo-0.0.1-SNAPSHOT.jar //home/ec2-user/

            # Run the Spring Boot application
            java -jar /home/ec2-user/demo-0.0.1-SNAPSHOT.jar
